/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import TopHeader from "./TopHeader";
import Navigation from "./Navigation";
import CartItems from "./CartItems";
import CartSummary from "./CartSummary";
import Footer from "./Footer";

const CartPage = () => {
  return (
    <StyledCartPage>
      <TopHeader />
      <main className="cart-main">
        <Navigation />
        <CartItems />
        <CartSummary />
      </main>
      <Footer />
    </StyledCartPage>
  );
};

const StyledCartPage = styled.div`
  background-color: #fff;
  display: flex;
  flex-direction: column;
  overflow: hidden;
`;

export default CartPage;
