/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const Footer = () => {
  return (
    <StyledFooter>
      <div className="footer-content">
        <div className="footer-section">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b8b3964a594d0bf681ac03e8b29d3b19df8e651a4dec5aff881596840465db90?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt="Company Logo"
            className="footer-logo"
          />
          <h3>Subscribe</h3>
          <p>Get 10% off your first order</p>
          <form className="subscribe-form">
            <input
              type="email"
              placeholder="Enter your email"
              aria-label="Enter your email for newsletter"
            />
            <button type="submit" aria-label="Subscribe">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/12a54082781a806227ade42d81d6722495cd51ed50c28a6b5eebf5a1f9d88295?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
                alt=""
              />
            </button>
          </form>
        </div>
        <div className="footer-section">
          <h3>Support</h3>
          <address>
            5th Avenue Broadway street NY
            <br />
            nonstop@gmail.com
            <br />
            +254-733-435-531
          </address>
        </div>
        <div className="footer-section">
          <h3>Account</h3>
          <nav>
            <ul>
              <li>
                <a href="/account">My Account</a>
              </li>
              <li>
                <a href="/login">Login / Register</a>
              </li>
              <li>
                <a href="/cart">Cart</a>
              </li>
              <li>
                <a href="/wishlist">Wishlist</a>
              </li>
              <li>
                <a href="/shop">Shop</a>
              </li>
            </ul>
          </nav>
        </div>
        <div className="footer-section">
          <h3>Quick Link</h3>
          <nav>
            <ul>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/about">About Us</a>
              </li>
              <li>
                <a href="/products">Our Products</a>
              </li>
              <li>
                <a href="/contact">Contact</a>
              </li>
              <li>
                <a href="/faq">FAQ</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <div className="payment-methods">
        <h3>Payment Methods</h3>
        <div className="payment-icons">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/828fef6076a9340ad48fbb61acff47dffc6648662d11b0419a4a7d1948fd9701?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt="Payment method 1"
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/10a8b1de3ddc22f993493ab0c895f05962db8156358bf093801162708794ef7f?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt="Payment method 2"
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b3f931b5bb46bd78352bd88a0131d5a7239a1e768a4cb1564c39797501a7c090?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt="Payment method 3"
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/38c3a24868d6753cc3b406df95413ccdcf2f16af0a3c085cef0e46f89efd9656?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt="Payment method 4"
          />
        </div>
      </div>
      <div className="footer-bottom">
        <hr />
        <div className="copyright">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e523e6062971c2f8fb3afd65bf0809c79bd696c629b217ba8b7cb3d63aa3bd1?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt=""
          />
          <p>Copyright nonstop@2024 All rights reserved</p>
        </div>
      </div>
    </StyledFooter>
  );
};

const StyledFooter = styled.footer`
  background-color: #000;
  color: #fafafa;
  padding: 52px 55px 0;
  font-family: Poppins, sans-serif;

  .footer-content {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 40px;
  }

  .footer-section {
    flex: 1;
    min-width: 200px;
  }

  .footer-logo {
    width: 200px;
    margin-bottom: 24px;
  }

  h3 {
    font-size: 20px;
    font-weight: 500;
    margin-bottom: 24px;
  }

  .subscribe-form {
    display: flex;
    margin-top: 16px;
  }

  .subscribe-form input {
    flex-grow: 1;
    padding: 12px;
    border: 1.5px solid #fafafa;
    background: transparent;
    color: #fafafa;
  }

  .subscribe-form button {
    background: none;
    border: none;
    padding: 0 16px;
    cursor: pointer;
  }

  address {
    font-style: normal;
    line-height: 1.5;
  }

  ul {
    list-style: none;
    padding: 0;
  }

  li {
    margin-bottom: 16px;
  }

  a {
    color: #fafafa;
    text-decoration: none;
  }

  .payment-methods {
    margin-top: 40px;
  }

  .payment-icons {
    display: flex;
    gap: 8px;
  }

  .payment-icons img {
    width: 42px;
    height: 28px;
  }

  .footer-bottom {
    margin-top: 60px;
  }

  hr {
    border: none;
    border-top: 1px solid rgba(255, 255, 255, 0.4);
    margin-bottom: 16px;
  }

  .copyright {
    display: flex;
    align-items: center;
    gap: 6px;
    justify-content: center;
    padding-bottom: 16px;
  }

  @media (max-width: 991px) {
    padding: 40px 20px 0;

    .footer-content {
      flex-direction: column;
    }

    .footer-section {
      width: 100%;
    }
  }
`;

export default Footer;
