/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const Navigation = () => {
  return (
    <StyledNavigation>
      <div className="logo-container">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b8b3964a594d0bf681ac03e8b29d3b19df8e651a4dec5aff881596840465db90?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
          alt="Company Logo"
          className="logo"
        />
      </div>
      <nav className="main-nav">
        <ul>
          <li>
            <a href="/">Home</a>
          </li>
          <li>
            <a href="/contact">Contact</a>
          </li>
          <li>
            <a href="/about">About</a>
          </li>
          <li>
            <a href="/signup">Sign Up</a>
          </li>
        </ul>
      </nav>
      <div className="search-cart">
        <form className="search-form" role="search">
          <label htmlFor="search-input" className="visually-hidden">
            Search
          </label>
          <input
            type="search"
            id="search-input"
            placeholder="What are you looking for?"
          />
          <button type="submit" aria-label="Search">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a36546edd30f9649053810fdbf6c98d92541e863e7b8b10ab13af855343b34e?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
              alt=""
            />
          </button>
        </form>
        <div className="cart-icons">
          <button aria-label="View wishlist">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2f46b01d8f56846dabad72a61fd444f3085a8b624cfad99f0b703fb6b78182f5?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
              alt=""
            />
          </button>
          <button aria-label="View cart">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/1d49936bb7e7947951a24074df0be75fc667e72893b1780ac9e82c006a87816b?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
              alt=""
            />
          </button>
          <button aria-label="View profile">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/505a01368e57ac667ecd551fd161eb3fa8202cee72841e5b11d9f712055e4607?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
              alt=""
            />
          </button>
        </div>
      </div>
    </StyledNavigation>
  );
};

const StyledNavigation = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 70px;
  font-family: Poppins, sans-serif;

  .logo {
    width: 200px;
  }

  .main-nav ul {
    display: flex;
    gap: 48px;
    list-style: none;
  }

  .main-nav a {
    color: #000;
    text-decoration: none;
  }

  .search-cart {
    display: flex;
    align-items: center;
    gap: 24px;
  }

  .search-form {
    display: flex;
    align-items: center;
    background-color: #f5f5f5;
    border-radius: 4px;
    padding: 7px 12px;
  }

  .search-form input {
    border: none;
    background: none;
    font-size: 12px;
    width: 200px;
  }

  .search-form button,
  .cart-icons button {
    background: none;
    border: none;
    cursor: pointer;
  }

  .cart-icons {
    display: flex;
    gap: 16px;
  }

  .visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }

  @media (max-width: 991px) {
    flex-direction: column;
    align-items: flex-start;
    padding: 20px;

    .main-nav,
    .search-cart {
      width: 100%;
      margin-top: 20px;
    }

    .main-nav ul {
      flex-wrap: wrap;
    }
  }
`;

export default Navigation;
