/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const FooterSection = ({ title, links }) => {
  return (
    <Section>
      <SectionTitle>{title}</SectionTitle>
      {links && (
        <LinkList>
          {links.map((link, index) => (
            <LinkItem key={index}>
              <LinkAnchor href={link.href}>{link.text}</LinkAnchor>
            </LinkItem>
          ))}
        </LinkList>
      )}
    </Section>
  );
};

const Section = styled.div`
  display: flex;
  margin: 0 5rem;
  flex-direction: column;
  justify-content: start;
`;

const SectionTitle = styled.h3`
  font-size: 20px;
  font-weight: 500;
  line-height: 1.4;
  color: var(--Text, #fafafa);
  margin: 0 0 24px;
`;

const LinkList = styled.ul`
  list-style: none;
  padding: 0;
  margin: 0;
`;

const LinkItem = styled.li`
  margin-bottom: 16px;
`;

const LinkAnchor = styled.a`
  font-size: 16px;
  font-weight: 400;
  color: var(--Text, #fafafa);
  text-decoration: none;
  &:hover {
    text-decoration: underline;
  }
`;

export default FooterSection;
