/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const SocialLinks = () => {
  return (
    <SocialLinksWrapper>
      <SocialIcon
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/31106ccf7f9b47cd488fefba20d096b1d7303864f7c967b7ee43968ac28ce833?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
        alt="Social Media Icon"
      />
    </SocialLinksWrapper>
  );
};

const SocialLinksWrapper = styled.div`
  display: flex;
  align-items: center;
`;

const SocialIcon = styled.img`
  width: 20px;
  height: 20px;
`;

export default SocialLinks;
