/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const SubscribeForm = () => {
  return (
    <FormWrapper>
      <SubscribeText>Get 10% off your first order</SubscribeText>
      <Form>
        <Label htmlFor="emailInput" className="visually-hidden">
          Enter your email
        </Label>
        <EmailInput
          type="email"
          id="emailInput"
          placeholder="Enter your email"
          aria-label="Enter your email"
        />
        <SubmitButton type="submit" aria-label="Subscribe">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/82bea2c24624aec83b7f465f3f7dd6459b56a1974408d3a52263051296213050?placeholderIfAbsent=true&apiKey=198507df3fb1499aa3645c6bf5866884"
            alt="Send"
          />
        </SubmitButton>
      </Form>
    </FormWrapper>
  );
};

const FormWrapper = styled.div`
  display: flex;
  flex-direction: column;
  width: 217px;
`;

const SubscribeText = styled.p`
  font-size: 16px;
  font-weight: 400;
  color: var(--Text, #fafafa);
  margin: 0 0 16px;
`;

const Form = styled.form`
  display: flex;
  align-items: center;
  border-radius: 4px;
  border: 1.5px solid var(--Text, #fafafa);
  padding: 12px 16px;
`;

const Label = styled.label`
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
`;

const EmailInput = styled.input`
  background: transparent;
  border: none;
  color: var(--Text, #fafafa);
  font-size: 16px;
  font-weight: 400;
  width: 100%;
  &::placeholder {
    opacity: 0.4;
  }
  &:focus {
    outline: none;
  }
`;

const SubmitButton = styled.button`
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 0;
  img {
    width: 24px;
    height: 24px;
  }
`;

export default SubscribeForm;
